// Rebuild the static, accessible story markup from JenerOS's existing artwork.
// No runtime templating, remote art, or new icon vocabulary.
const fs = require('node:fs');
const file = '[SITE]/preview.html';
const original = fs.readFileSync(file, 'utf8');
const sprite = fs.readFileSync('[DASHBOARD]/icons.svg', 'utf8');
const icon = name => `<svg aria-hidden="true" viewBox="0 0 24 24"><use href="#i-${name}"/></svg>`;
const symbols = ['files','apps','photos','backup','machines','disk','check','settings'].map(name => sprite.match(new RegExp(`<symbol id="i-${name}"[\\s\\S]*?</symbol>`))[0]).join('\n');
const mark = fs.readFileSync('[SITE]/assets/logo/jeneros-wordmark-light.svg','utf8');
const letters = [...mark.matchAll(/<!-- (?:J|E|N|R:[^>]*|O|S) -->\s*(<path[^>]+\/>)/g)].map(m => `<g class="letter">${m[1]}</g>`).join('');
if (letters.match(/class="letter"/g)?.length !== 7) throw Error('Expected seven brand letter paths');
const wordmark = `<svg class="wordmark" viewBox="0 0 1136 144" aria-hidden="true">${letters}</svg>`;
const screen = (name, cls, alt, phone = false) => `<figure class="screen ${cls}"><picture><source media="(prefers-color-scheme: dark)" srcset="assets/shots/${name}.webp ${phone?390:1280}w, assets/shots/${name}@2x.webp ${phone?780:2560}w" sizes="${phone?'(min-width: 900px) 18vw, 30vw':'(min-width: 1800px) 1400px, 88vw'}"><img src="assets/shots/${name}-light.webp" srcset="assets/shots/${name}-light.webp ${phone?390:1280}w, assets/shots/${name}-light@2x.webp ${phone?780:2560}w" sizes="${phone?'(min-width: 900px) 18vw, 30vw':'(min-width: 1800px) 1400px, 88vw'}" width="${phone?390:1280}" height="${phone?844:800}" decoding="async" ${name==='dashboard'?'':'loading="lazy"'} alt="${alt}"></picture><span class="specular" aria-hidden="true"></span></figure>`;
const tiles = () => `<div class="tile-shelf" aria-hidden="true">${[['files','Files'],['apps','App Store'],['photos','Photos'],['backup','Backup'],['machines','Machines']].map(([id,label])=>`<div class="app-tile tile-${id}">${icon(id)}<span>${label}</span><i class="specular"></i></div>`).join('')}</div>`;
const words = (...lines) => `<div class="word-card" aria-hidden="true">${lines.map(t=>`<span>${t}</span>`).join('')}</div>`;
const chip = (cls, text) => `<div class="chip ${cls}"><span class="chip-glass" aria-hidden="true"></span><span class="chip-content">${icon('check')}${text}</span></div>`;
const chapter = (id, beats, title, caption, content, word = '') => `<section class="chapter chapter-${id}" id="${id}" data-scene="${id}" data-beats="${beats}" aria-labelledby="${id}-title"><div class="stage"><div class="scene-glow" aria-hidden="true"></div><div class="ribbon ribbon-far" aria-hidden="true"></div><div class="ribbon ribbon-near" aria-hidden="true"></div><div class="camera">${content}</div>${word}<div class="caption"><h2 id="${id}-title"><span>${title}</span></h2><p>${caption}</p></div></div></section>`;
const box = `<div class="box" aria-hidden="true"><div class="box-top"></div><div class="box-front"><img src="assets/logo/j-monogram-light.svg" alt="" width="60" height="60"><i class="power-light"></i><span class="box-slot"></span></div><div class="box-side"></div></div>`;
const story = [
chapter('hero',8,'Your stuff lives at home.','A new life for your old PC. One home for the things you love.',`<div class="hero-brand"><h1 class="sr-only">JenerOS</h1>${wordmark}<p>Make yourself at home.</p></div><div class="hero-product">${screen('dashboard','primary','JenerOS dashboard with clock, system readings, storage, network and apps.')}${box}<div class="boot-logo" aria-hidden="true"><img src="assets/logo/j-monogram-light.svg" alt="" width="96" height="96"></div></div><span class="scroll-hint">Scroll to explore <span aria-hidden="true">&darr;</span></span>`),
chapter('macro',4,'Everything, right here.','Files, photos, backups and machines. A familiar place to begin.',`<div class="bar-macro">${screen('dashboard','primary','A closer look at the dashboard and its top bar.')}</div>${tiles()}`),
chapter('widget',8,'Your stuff. Lives at home.','See how your box is doing, without digging through menus.',`<div class="widget-morph"><div class="widget-shape"></div><div class="widget-content"><span>Your box, at a glance</span><div class="cpu"><svg viewBox="0 0 120 120" aria-hidden="true"><circle class="ring-track" cx="60" cy="60" r="50"/><circle class="ring-value" cx="60" cy="60" r="50" pathLength="100"/></svg><strong><span data-count="24">24</span><small>%</small></strong></div><p>CPU &middot; plenty of room</p><div class="widget-storage"><span>Storage</span><b>186 GB free</b></div></div><div class="widget-seed" aria-hidden="true">${icon('machines')}</div></div>`,words('Your stuff.','Lives at home.')),
chapter('phone',8,'Set up from your phone.','Scan the code on your box. Make it yours from the comfort of your phone.',`${screen('setup-welcome','primary','The real welcome screen with language, privacy consent and setup code.')}${box}${screen('phone-setup','phone','The same setup on a phone.',true)}<div class="qr-detail" aria-hidden="true"><img src="assets/preview-qr.svg" alt="" width="120" height="120"><span>Scan. You&apos;re home.</span></div><svg class="connection" viewBox="0 0 600 240" aria-hidden="true"><path d="M80 120C240 120 300 200 470 110" pathLength="1"/></svg>${chip('connected','Connected')}`,words('Set up','from your phone.')),
chapter('settings',4,'A place for every setting.','Your box, your preferences. All together in one calm window.',`${screen('dashboard','before','Dashboard before opening Settings.')}${screen('settings-general','primary','Settings General: box information, appearance and preferences.')}<div class="sidebar-highlight" aria-hidden="true"></div>`),
chapter('storage',12,'Storage in a few taps.','See your disks. Pick a mirror to keep a second copy. Every choice, explained before you erase.',`${screen('settings-storage','primary','Storage settings with disk bays, the system disk and Create storage.')}<div class="storage-detail"><div class="disk-bays" aria-hidden="true">${[1,2,3].map(i=>`<div class="bay"><div class="disk">${icon('disk')}<b>${i===3?'4':'2'} TB</b><span>Disk ${i}</span></div></div>`).join('')}</div><div class="mirror"><span>Two disks. One safe place.</span><div class="mirror-track"><i></i></div><p><b data-count="100">100</b>% mirrored <span>Illustration</span></p></div>${chip('storage-ready','Your storage is ready')}</div>`,words('Storage')),
chapter('updates',8,'Updates that undo themselves.','If an update cannot start, your box goes back to the working version. Your files stay put.',`${screen('settings-general','primary','The real system Settings screen.')}<div class="system-cards"><div class="system-card system-a"><span>Previous system</span><strong>Ready when you need it.</strong><small>Your files stay put.</small></div><div class="system-card system-b"><span>New system</span><strong>A fresh start.</strong><small>A second system keeps your place.</small></div>${chip('update-safe','Back to the working version')}</div>`,words('Updates','that undo themselves.')),
chapter('apps',8,'Your own app store.','Photos, movies, files and your smart home. The store is here; apps arrive one by one.',`${screen('store-discover','primary','App Store Discover with Photos, TV, Drive, Home and Relay.')}${tiles()}`,words('Your own','app store.')),
chapter('finale',8,'Free. Open source. Yours.','Bring your stuff home.',`<div class="orbit">${screen('settings-general','orbit-screen','Settings in the closing screen stack.')}${screen('settings-storage','orbit-screen','Storage in the closing screen stack.')}${screen('store-discover','orbit-screen','App Store in the closing screen stack.')}${screen('dashboard','orbit-screen','Dashboard in the closing screen stack.')}${screen('phone-dashboard','orbit-screen orbit-phone','Dashboard on a phone.',true)}</div>${box}<div class="final-brand">${wordmark}<p>Free. Open source. Yours.</p><div class="actions"><a class="btn btn-primary" href="download.html">Download<span class="specular" aria-hidden="true"></span></a><a class="btn btn-ghost" href="https://github.com/PrimeExtremo/JenerOS">GitHub<span class="specular" aria-hidden="true"></span></a></div></div>`)
].join('\n');
const main = `<main id="main"><div class="tour-tools" hidden><button type="button" id="motion-toggle" aria-pressed="false">Still view</button><button type="button" id="trailer-pause" hidden>Pause trailer</button><a href="#finale">Skip to download</a><span id="trailer-status" role="status"></span></div><div class="story">${story}</div><div class="wrap preview-note"><p>Early preview. Real JenerOS screens with sample readings. The connection, storage and update animations illustrate how it works. App installation is still on the way.</p><p><a href="assets/video/jeneros-preview.mp4">Earlier preview film (16:9)</a> &middot; <a href="assets/video/jeneros-preview-vertical.mp4">Earlier vertical film (9:16)</a></p></div></main>`;
const defs = `<svg class="glass-defs" width="0" height="0" aria-hidden="true" focusable="false"><defs><filter id="glass" x="-10%" y="-10%" width="120%" height="120%" color-interpolation-filters="sRGB"><feTurbulence type="fractalNoise" baseFrequency=".018 .025" numOctaves="1" seed="11" result="noise"/><feDisplacementMap in="SourceGraphic" in2="noise" scale="2" xChannelSelector="R" yChannelSelector="G"/></filter>${symbols}</defs></svg>`;
fs.writeFileSync(file, original.replace(/<!-- Liquid glass:[\s\S]*?<header/, defs+'\n<header').replace(/<main id="main">[\s\S]*?<\/main>/, main).replace('<!-- Small and blocking on purpose: it picks the 3D story or the still grid before the first paint. -->','<!-- The still grid is the default. Motion starts only after the story is ready. -->').replace('<script src="assets/preview.js"></script>','<script src="assets/preview.js" defer></script>'));
