// No packages needed. QR fixtures were generated by qrcodejs's upstream model
// at blob 5507c154ffc1b9d061c55d88268a26eeba49a36e (Version 5, L, mask 0).
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const path = require('node:path');
const repo = path.resolve(__dirname, '../..');
class Element {
  constructor() { this.attributes = {}; this.children = []; }
  setAttribute(key, value) { this.attributes[key] = String(value); }
  append(...children) { this.children.push(...children); }
}
const context = { window: {}, TextEncoder, document: { createElementNS: () => new Element() } };
vm.runInNewContext(fs.readFileSync(path.join(repo, '[DASHBOARD]/vendor/qrcode.js'), 'utf8'), context);
const fixtures = JSON.parse(fs.readFileSync(path.join(__dirname, 'qr-fixtures.json'), 'utf8'));
for (const { text, hash } of fixtures) {
  const element = new Element();
  new context.window.QRCode(element, { text });
  const svg = element.children[0];
  assert.equal(svg.attributes.viewBox, '0 0 45 45'); // Four quiet modules on every side.
  const modules = Array.from({ length: 37 }, () => Array(37).fill(false));
  for (const match of svg.children[1].attributes.d.matchAll(/M(\d+),(\d+)h1v1h-1z/g)) modules[Number(match[2]) - 4][Number(match[1]) - 4] = true;
  const actual = crypto.createHash('sha256').update(JSON.stringify(modules)).digest('hex');
  assert.equal(actual, hash, `QR differs from upstream for ${text}`);
}
assert.throws(() => new context.window.QRCode(new Element(), { text: 'x'.repeat(107) }), /too long/);
console.log(`QR checks passed: ${fixtures.length} upstream matrix fixtures, quiet zone, overflow.`);
